package model;

public class Subproject {
    private int id;
    private String name;
    private int completionPercentage;
    private StateStatus status;
    private int projectId;


    /** No-args constructor – required by frameworks and libraries like RowMapper **/
    public Subproject() {
    }

    /** Constructor with all fields except 'id', as it will be auto-generated by the database **/
    public Subproject(String name, int completionPercentage, StateStatus status, int projectId) {
        this.name = name;
        this.completionPercentage = completionPercentage;
        this.status = status;
        this.projectId = projectId;
    }

    /** Overloaded constructor with optional fields **/
    public Subproject(String name, int projectId){
        this.name = name;
        this.projectId = projectId;
        this.completionPercentage = 0;           /** Default value **/
        this.status = StateStatus.NOT_STARTED;   /** Default value **/
    }

    /** Getter methods **/
    public int getProjectId() {
        return projectId;
    }

    public StateStatus getStatus() {
        return status;
    }

    public int getCompletionPercentage() {
        return completionPercentage;
    }

    public String getName() {
        return name;
    }

    public int getId() {
        return id;
    }

    /** Setter methods **/
    public void setId(int id) {
        if (id < 0)
            throw new IllegalArgumentException("ID kan ikke være mindre end 0.");
        this.id = id;
    }

    public void setName(String name) {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Navnet kan ikke være null eller tomt.");
        }
        if (name.length() < 4) {
            throw new IllegalArgumentException("Navnet skal være mindst 4 tegn langt.");
        }
        if (!Character.isUpperCase(name.charAt(0))) {
            throw new IllegalArgumentException("Navnet skal starte med et stort bogstav.");
        }
        this.name = name;
    }

    public void setCompletionPercentage(int completionPercentage) {
        if (completionPercentage < 0 || completionPercentage > 100) {
            throw new IllegalArgumentException("Fuldførelsesprocenten skal være mellem 0 og 100.");
        }
        this.completionPercentage = completionPercentage;
    }
    public void setStatus(StateStatus status){
        if (status == null) {
            throw new IllegalArgumentException("Status kan ikke være null.");
        }
        this.status = status;
    }

    public void setProjectId(int projectId) {
        if (projectId <= 0) {
            throw new IllegalArgumentException("Projekt-ID kan ikke være mindre end 0.");
        }
        this.projectId = projectId;
    }

    /** Override toString() method for better readability **/
    @Override
    public String toString() {
        return "Subproject{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", completionPercentage=" + completionPercentage +
                ", status=" + status +
                ", projectId=" + projectId +
                '}';
    }
}
